### ISSUE TITLE
Artist Open studio + An Xiao Mina

### ISSUE THREAD

**Issue by Saallen** [MozillaFoundation/mozfest-program-2017#848]
[ UUID ] 

[ Session Name ] Artist Open studio + An Xiao Mina
[ Primary Space ] Web LIteracy
[ Secondary Space ] 

[ Submitter's Name ] An Xiao Mina

[ Additional facilitators ] 

Technologist, writer and artist, An Xiao Mina, leads the product team at Meedan where they are building Check, a platform for collaboratively verifying news in real time, and Bridge, a platform for translating social media and messaging app content. 
An Xiao is also a 2017 Fellow at Harvard University’s Berkman Klein Center for Internet and Society and she is currently working on "From Memes to Movements" a book about internet memes and global social movements, to be published in 2018 by Beacon Press.

An Xiao Mina has been invited to respond to the Web Literacy issue area by
presenting a participatory installation and engaging visitors in related activity.

Artist website- https://about.me/anxiaostudio

Media/Approach -

If your session requires additional materials or electronic equipment, please outline your needs.

Time needed

All weekend, as an installation, exhibit or drop-in session

**Comment by marcwalsh** [comment]
Closing - Submitted incorrectly.
