### ISSUE TITLE
Artist Open Studio + Paolo Cirio

### ISSUE THREAD

**Issue by EsmeSimcox** [MozillaFoundation/mozfest-program-2017#849]
[ UUID ]

[ Session Name ] Artist Open Studio + Paolo Cirio
[ Primary Space ] Privacy & Security
[ Secondary Space ] 

[ Submitter's Name ] Paolo Cirio

[ Additional facilitators ] 

Paolo Cirio’s art practice considers how society is affected by the distribution, organization, and control of information. He engages with legal, economic, and semiotic systems of the information society embodying in his practice hacker ethics, such as open access, privacy policies, and disrupting economic, legal, and political models. His works investigates social fields impacted by the Internet, such as privacy, copyright, democracy, and finance.

Paolo Cirio will be exploring the Privacy and Security issue area by presenting a participatory installation and engaging visitors in related activity.

Artist Website: https://www.paolocirio.net

Media/Approach - Generic for now

Time needed:
All weekend, as an installation, exhibit or drop-in session

**Comment by bunnybooboo** [comment]
CONGRATULATIONS! Your session proposal has been accepted. 

I know Paolo was selected by the Mozfest Production committee, but why should he miss out on being congratulated by the P&S team hey? Congrats Paolo!!!!!!!!

**Comment by marcwalsh** [comment]
Closing - Submitted incorrectly.
