### ISSUE TITLE
Artist Open Studio + Archana Prasad 

### ISSUE THREAD

**Issue by EsmeSimcox** [MozillaFoundation/mozfest-program-2017#850]
[ UUID ]

[ Session Name ] Artist Open Studio + Archana Prasad 
[ Primary Space ] Decentralisation
[ Secondary Space ]

[ Submitter's Name ] Archana Prasad 

[ Additional facilitators ]

Archana, whose work brings together visual art, technology and urban community art, steeped in design and research methodologies, has been actively engaged with community art practices for the last decade. She is also the founder-director of Jaaga, a community based urban art, tech and activism project in Bangalore, India.

Archana Prasad will be responding to the Decentralisation issue area with a participatory installation and engaging visitors in related activity.  

Artist Website: http://www.archanaprasad.com

Media/Approach - Generic for now

Time needed:
All weekend, as an installation, exhibit or drop-in session

**Comment by cubicgarden** [comment]
Great I'd like to introduce #565 together

**Comment by cubicgarden** [comment]
Great I'd like to introduce #565 together

**Comment by marcwalsh** [comment]
Closing - Submitted incorrectly.
