### ISSUE TITLE
Artist Open Studio + Gretta Louw 

### ISSUE THREAD

**Issue by EsmeSimcox** [MozillaFoundation/mozfest-program-2017#851]
[ UUID ]

[ Session Name ] Artist Open Studio + Gretta Louw 
[ Primary Space ] Open Innovation
[ Secondary Space ]

[ Submitter's Name ] Gretta Louw 

[ Additional facilitators ]

German-Australian artist, curator and writer, Gretta Louw, is working predominantly with digital media and networked performance. Her artistic practice explores how new digital technologies are shaping our life, identity and contemporary experience, and the potential of art as a means of investigating psychological phenomena, particularly in relation to new technologies and the internet.

Gretta Louw will be based in and exploring the Open Innovation space with a participatory installation and engaging visitors in related activity.  

Artist Website: http://www.grettalouw.com 

Media/Approach - Generic for now

Time needed:
All weekend, as an installation, exhibit or drop-in session

**Comment by marcwalsh** [comment]
Closing - Submitted incorrectly.
