### ISSUE TITLE
Artist Open Studio + Brooklyn J. Pakathi

### ISSUE THREAD

**Issue by EsmeSimcox** [MozillaFoundation/mozfest-program-2017#852]
[ UUID ]

[ Session Name ] Artist Open Studio + Brooklyn J. Pakathi
[ Primary Space ] Digital Inclusion
[ Secondary Space ]

[ Submitter's Name ] Brooklyn J. Pakathi

[ Additional facilitators ]

South African filmmaker and photographer, Brooklyn Pakathi’s work explores the self, identity, youth culture and how technology and the internet can shape these. Often his online films and photos address experiences of contemporary youth culture in the age of the internet, desires and clashing worlds of real-unreal, physical-virtual.

Will be responding to the Digital Inclusion issue area with a participatory installation and engaging visitors in related activity.  

Artist Website: https://brooklynpakathi.com  

Media/Approach - Generic for now

Time needed:
All weekend, as an installation, exhibit or drop-in session

**Comment by marcwalsh** [comment]
Closing - Submitted incorrectly.
