### ISSUE TITLE
Do we live in the world where inclusion is for all?

### ISSUE THREAD

**Issue by EsmeSimcox** [MozillaFoundation/mozfest-program-2017#853]
[ UUID ] 

[ Session Name ] Do we live in the world where inclusion is for all?
[ Primary Space ] Youth Zone
[ Secondary Space ] Privacy & Security

[ Submitter's Name ] Hannah Prentice

[ Additional facilitators ] 

Session Name:
Do we live in a world where inclusion is for all?

Session Plan:
Start of session, I will introduce myself and speak bit about my background [living with Tourettes] and why I am here today at Mozilla fest. I will set them a task to work in pairs/groups of three, to discuss the topic inclusion for all [- how can we support everyone in society to have a voice even if they might struggle in day to day life with this].  Then we  plan how they will present it through an accessible artform. They go and explore the space at Mozilla fest, gather any evidence/inspiration to then on to creating, this will take the longest. I would assist anyone that needs ideas or help. Then final part is a group presentation back about their piece, explain why they have created this piece. 

Goals/outcomes of session:
In the session,  participants create pieces of artwork that publish online/put up artwork around different of spaces of Mozilla Fest to display. The artwork topic is [“How can we enable everyone to express their reasonable voice without fear of retaliation”]. Do we live in a world where inclusion is for all?  I will give examples to suggest idea for the artwork, like drawings, poetry recording small soundbites, interviewing a person, collage, typography, stenciling.

After festival:
They can take the artwork they have created. I am hoping they take an new approach on how to see the world can be a place inclusion for all, in the smallest things us human do.  [Even if you don’t feel you can express your voice usually, the fact that the internet can provide a place which feels comfortable enough- private and secure among friends and family - to express themselves.] If they feel passionate about inclusion for all, want to share your voice, express it through an artform. I would aso like to take a scan copy/photo of their work to present in a zine my creating myself. 

Numbers of particants:
Say if 30 particants attend that be great, I would keep to the session plan, any even someone group. I either would shorten the length of the session to 1 hour/give them more artwork to create/have a group discussion why they are here today?

Session Materials:
Projector, plain white paper, scissors, felt tip/coloured markers, water colours, oil pastels, glue sticks/pva glue, ask the particants to bring a small phone/tablets to take photos. And somewhere I could possible print.

Time needed:
60-90 mins

**Comment by EPIKhub** [comment]
@EsmeSimcox I'm not at home until Monday, could you email me contact details for this session leader please?

**Comment by EsmeSimcox** [comment]
@EPIKhub I will send it over to you now

**Comment by emrysgreen** [comment]
Hi @EPIKhub - this is from one of my young leaders and Arts Award will cover her travel along with an adviser to support her.  I'm hoping @bunnybooboo and team will accept it as part of youth led track to the Privacy & Security space.

@bunnybooboo - we can shape the session to ensure it meets your specific outcome needs for sessions in your space.  Including making it a shorter sub-60 minute session, and the session content can be geared.  I'll be working to support her on final planning and delivery.

Thanks all.

**Comment by EPIKhub** [comment]
@emrysgreen ok so not really submitted for the youth zone as you said you are not running any arts award in the youth zone, I'll remove milestone.

**Comment by emrysgreen** [comment]
Sure, thanks.

**Comment by bunnybooboo** [comment]
@emrysgreen Pending schedule decision. It's on the desk.

**Comment by bunnybooboo** [comment]
CONGRATULATIONS! Your session proposal has been accepted.

Hannah our team will be in further contact with you via email in the coming days.

cc/ @emrysgreen

**Comment by emrysgreen** [comment]
Wonderful, thanks @bunnybooboo

**Comment by marcwalsh** [comment]
Closing - Submitted incorrectly. Replaced with #860
