### ISSUE TITLE
Hi @auremoser would it be possible to edit the name to 'Alex Pearson'? Thanks

### ISSUE THREAD

**Issue by Lexacious** [MozillaFoundation/mozfest-program-2017#874]
Please do not submit session proposals directly through Github. Instead, submit your session through the [Call For Proposals form](https://mozillafestival.org/proposals).

If you submit your session directly though Github it will not receive the unique identifiers required for the curation process and inclusion in the final schedule. 

Thanks,
The MozFest Team

**Comment by KirstieJane** [comment]
Hi @Saallen @edrushka @marcwalsh - what's this issue? Do you have any idea where it came from?

@auremoser - you might know?

**Comment by Lexacious** [comment]
Hi all,

I'm so sorry I was requesting a change of the submitters name to 'Alex
Pearson' as the name listed for the Future Aleppo workshop was incorrect.

Sorry I have never used github before so I think I requested the edit
wrongly.

Apologies,

Alex

**Comment by KirstieJane** [comment]
Gotcha! It's updated here: https://github.com/MozillaFoundation/mozfest-program-2017/issues/19

I'm going to close this issue :smile:

See you at MozFest!

**Comment by edrushka** [comment]
No problem, Alex. We all had to learn, Github, too 😃 Great to see you getting started!
Erika
